PHQ9 = (
    "Your task is to write a response to a question, "
    "as if you were a person whose PHQ-9 item scores are given. "
    "\n\n"

    "The PHQ-9 is a 9-item depression screening questionnaire. The 9 items are:\n"
    "- Anhedonia: Little interest or pleasure in doing things\n"
    "- Depressed Mood: Feeling down, depressed, or hopeless\n"
    "- Insomnia or Hypersomnia: Trouble falling or staying asleep, or sleeping too much\n"
    "- Fatigue: Feeling tired or having little energy\n"
    "- Poor Appetite or Overeating\n"
    "- Worthlessness or Guilt: Feeling bad about yourself or that you are a failure "
    "or have let yourself or your family down\n"
    "- Difficulty Concentrating: Trouble concentrating on things\n"
    "- Psychomotor Agitation or Retardation: Moving or speaking so slowly that other "
    "people could have noticed, or being so fidgety or restless that you have been "
    "moving around a lot more than usual\n"
    "- Suicidal Ideation: Thoughts that you would be better off dead, or of hurting yourself"
    "\n\n"

    "Each item is scored from 0 to 3, "
    "where 0 means the symptom was not experienced and 3 means it was experienced at a high severity. "
    "The total score ranges from 0 to 27 and falls into one of these categories: "
    "None (0-4), Mild (5-9), Moderate (10-14), Moderately Severe (15-19), and Severe (20-27)."
    "\n\n"

    "You will be given an input that follows this schema:\n"
    "{{\n"
    "    \"item_scores\": [\n"
    "        {{\"item\": \"<one of the 9 PHQ-9 items above>\", \"score\": <integer 0-3>}},\n"
    "        ...\n"
    "    ],\n"
    "    \"question\": \"<the question you must answer>\"\n"
    "}}\n"
    "'item_scores' is an array of 9 objects giving the per-item PHQ-9 score, "
    "and 'question' is the text you must answer."
    "\n\n"

    "Please follow these steps:\n"
    "STEP 1: For each entry in 'item_scores' with a non-zero 'score', think of one or "
    "more short phrases that a person with that 'item' might naturally say. The phrasing "
    "can mention the symptom directly or describe it indirectly (e.g., \"I don't see the "
    "point of getting out of bed\" can mean lack of interest). The phrasing should reflect "
    "the 'score': higher scores warrant more phrases and more severe wording (e.g., score "
    "1 -> \"a bit tired\"; score 3 -> \"completely exhausted every day\"). Skip entries "
    "whose 'score' is 0.\n"
    "STEP 2: Using the phrases from STEP 1 write a single first-person paragraph that "
    "answers the 'question'. Do not mention the PHQ-9, item names, numbers, or any clinical "
    "terms. Do not add disclaimers."
    "\n\n"

    "Format your output as a JSON with two fields: 'reason' summarizing the phrases you "
    "chose per non-zero 'item' (STEP 1), and 'text-response' containing the final paragraph "
    "from STEP 2. Elements inside angle brackets are placeholders for the actual values:\n"
    "{{\n"
    "    \"reason\": \"<short explanation of the chosen phrases per item>\",\n"
    "    \"text-response\": \"<single first-person paragraph>\"\n"
    "}}\n\n"

    "Input:\n{input}"
)


GAD7 = (
    "Your task is to write a response to a question, "
    "as if you were a person whose GAD-7 item scores are given. "
    "\n\n"

    "The GAD-7 is a 7-item generalized anxiety screening questionnaire. The 7 items are:\n"
    "- Nervousness: Feeling nervous, anxious, or on edge\n"
    "- Uncontrollable Worry: Not being able to stop or control worrying\n"
    "- Excessive Worry: Worrying too much about different things\n"
    "- Trouble Relaxing: Difficulty relaxing\n"
    "- Restlessness: Being so restless that it is hard to sit still\n"
    "- Irritability: Becoming easily annoyed or irritable\n"
    "- Apprehension: Feeling afraid, as if something awful might happen"
    "\n\n"

    "Each item is scored from 0 to 3, "
    "where 0 means the symptom was not experienced and 3 means it was experienced at a high severity. "
    "The total score ranges from 0 to 21 and falls into one of these categories: "
    "Minimal (0-4), Mild (5-9), Moderate (10-14), and Severe (15-21)."
    "\n\n"

    "You will be given an input that follows this schema:\n"
    "{{\n"
    "    \"item_scores\": [\n"
    "        {{\"item\": \"<one of the 7 GAD-7 items above>\", \"score\": <integer 0-3>}},\n"
    "        ...\n"
    "    ],\n"
    "    \"question\": \"<the question you must answer>\"\n"
    "}}\n"
    "'item_scores' is an array of 7 objects giving the per-item GAD-7 score, "
    "and 'question' is the text you must answer."
    "\n\n"

    "Please follow these steps:\n"
    "STEP 1: For each entry in 'item_scores' with a non-zero 'score', think of one or "
    "more short phrases that a person with that 'item' might naturally say. The phrasing "
    "can mention the symptom directly or describe it indirectly (e.g., \"my mind won't "
    "stop racing\" can mean uncontrollable worry). The phrasing should reflect the "
    "'score': higher scores warrant more phrases and more severe wording (e.g., score "
    "1 -> \"a little on edge\"; score 3 -> \"constantly panicking about everything\"). "
    "Skip entries whose 'score' is 0.\n"
    "STEP 2: Using the phrases from STEP 1 write a single first-person paragraph that "
    "answers the 'question'. Do not mention the GAD-7, item names, numbers, or any clinical "
    "terms. Do not add disclaimers."
    "\n\n"

    "Format your output as a JSON with two fields: 'reason' summarizing the phrases you "
    "chose per non-zero 'item' (STEP 1), and 'text-response' containing the final paragraph "
    "from STEP 2. Elements inside angle brackets are placeholders for the actual values:\n"
    "{{\n"
    "    \"reason\": \"<short explanation of the chosen phrases per item>\",\n"
    "    \"text-response\": \"<single first-person paragraph>\"\n"
    "}}\n\n"

    "Input:\n{input}"
)


PSS10 = (
    "Your task is to write a response to a question, "
    "as if you were a person whose PSS-10 item scores are given. "
    "\n\n"

    "The PSS-10 is a 10-item perceived stress scale measuring how often, during the "
    "last month, the person has felt the following. The 10 items are:\n"
    "- Upset by Unexpected Events: Been upset because of something that happened unexpectedly\n"
    "- Lack of Control: Felt unable to control the important things in your life\n"
    "- Nervous and Stressed: Felt nervous and stressed\n"
    "- Confidence in Coping (reverse): Felt confident about your ability to handle your personal problems\n"
    "- Things Going Your Way (reverse): Felt that things were going your way\n"
    "- Inability to Cope: Found that you could not cope with all the things you had to do\n"
    "- Control of Irritations (reverse): Been able to control irritations in your life\n"
    "- On Top of Things (reverse): Felt that you were on top of things\n"
    "- Anger at Things Outside Control: Been angered because of things outside of your control\n"
    "- Overwhelming Difficulties: Felt difficulties were piling up so high that you could not overcome them"
    "\n\n"

    "Each item is scored from 0 to 4, where 0 = Never, 1 = Almost Never, 2 = Sometimes, "
    "3 = Fairly Often, and 4 = Very Often. For the four reverse-scored items (marked "
    "'reverse' above) a higher raw score indicates lower stress; for the other items a "
    "higher raw score indicates higher stress. The total score ranges from 0 to 40 and "
    "falls into one of these categories: Low Stress (0-13), Moderate Stress (14-26), "
    "and High Perceived Stress (27-40)."
    "\n\n"

    "You will be given an input that follows this schema:\n"
    "{{\n"
    "    \"item_scores\": [\n"
    "        {{\"item\": \"<one of the 10 PSS-10 items above>\", \"score\": <integer 0-4>}},\n"
    "        ...\n"
    "    ],\n"
    "    \"question\": \"<the question you must answer>\"\n"
    "}}\n"
    "'item_scores' is an array of 10 objects giving the per-item PSS-10 score, "
    "and 'question' is the text you must answer."
    "\n\n"

    "Please follow these steps:\n"
    "STEP 1: For each entry in 'item_scores' think of one or more short phrases that a "
    "person with that experience might naturally say. For non-reverse items, treat a "
    "higher 'score' as more stress (e.g., score 1 -> \"a little overwhelmed sometimes\"; "
    "score 4 -> \"constantly drowning in stress\"). For reverse-scored items, treat a "
    "LOWER 'score' as more stress (e.g., score 0 on 'Confidence in Coping' -> \"I never "
    "feel like I can handle anything\"; score 4 -> \"I feel pretty in control of my "
    "problems\"). Skip items whose score does not reflect any stress signal in either "
    "direction (e.g., score 0 on a non-reverse item, or score 4 on a reverse item).\n"
    "STEP 2: Using the phrases from STEP 1 write a single first-person paragraph that "
    "answers the 'question'. Do not mention the PSS-10, item names, numbers, or any clinical "
    "terms. Do not add disclaimers."
    "\n\n"

    "Format your output as a JSON with two fields: 'reason' summarizing the phrases you "
    "chose per item (STEP 1), and 'text-response' containing the final paragraph "
    "from STEP 2. Elements inside angle brackets are placeholders for the actual values:\n"
    "{{\n"
    "    \"reason\": \"<short explanation of the chosen phrases per item>\",\n"
    "    \"text-response\": \"<single first-person paragraph>\"\n"
    "}}\n\n"

    "Input:\n{input}"
)


if __name__ == "__main__":
    print(PHQ9)
    print("\n\n===\n\n")
    print(GAD7)
    print("\n\n===\n\n")
    print(PSS10)
